### ISSUE TITLE
Switch language not work with Gettext

### ISSUE THREAD

**Issue by ifree321** [smpallen99/coherence#327] opened 2018-01-23 07:39 UTC
I found in the `coherence/coherence_view_helpers.ex` file:
`recover_link、unlock_link、register_link、invite_link、confirm_link、signin_link and signout_link` all of them are module attributes. But in `coherence_messages.ex` file:
all the text that need use Gettext are defined as function.
  When I switch language with plug, text defined in `layout/app.html.eex` file with ```Coherence.ViewHelpers.coherence_links(@conn, :layout)``` are not changed.
  So I changed module attributes in `coherence_view_helpers.ex` file to function like `coherence_message.ex` file, it worked.
Is it wrong for me to understand? What is the right way to realize it?
I'm not good at English. I don't know if you can understand it. I'm very sorry. #

**Comment by smpallen99** [comment] 2018-08-27 21:26
Gives us a little more time there too.

**Comment by smpallen99** [comment] 2018-08-27 21:38
You are right. `dgettext/2` must be called at run time and cannot be bound to a module attribute. I'll get a fix in soon.

**Comment by smpallen99** [comment] 2018-08-27 21:41
Duplicate of #322

**Closed** 2018-08-28 01:08 UTC
Labels: bug, duplicate
