### ISSUE TITLE
coherence cannot be built in prod mode

### ISSUE THREAD

**Issue by retrogradeorbit** [smpallen99/coherence#216] opened 2017-06-28 06:18 UTC
mix deps.tree gives me:

```
├── coherence ~> 0.3.1 (Hex package)
│   ├── comeonin ~> 2.4 (Hex package)
│   ├── ecto ~> 2.0 (Hex package)
│   ├── gettext ~> 0.11 (Hex package)
│   ├── phoenix ~> 1.2 (Hex package)
│   ├── phoenix_html ~> 2.6 (Hex package)
│   ├── phoenix_swoosh ~> 0.1.3 (Hex package)
│   │   ├── phoenix ~> 1.0 (Hex package)
│   │   ├── phoenix_html ~> 2.2 (Hex package)
│   │   └── swoosh ~> 0.1 (Hex package)
│   ├── phoenix_timex ~> 1.0.0 (Hex package)
│   │   ├── phoenix_html ~> 2.5 (Hex package)
│   │   └── timex ~> 2.1 (Hex package)
│   ├── timex_ecto ~> 1.1 (Hex package)
│   └── uuid ~> 1.0 (Hex package)
```
And building a production release with `MIX_ENV=prod mix release --env=prod` gives:

```
==> Failed to build release:
    
    Duplicated modules: 
    	'Elixir.Phoenix.HTML.Safe.DateTime' specified in phoenix_html and phoenix_timex
    	'Elixir.Phoenix.HTML.Safe.Date' specified in phoenix_html and phoenix_timex
```

**Comment by smpallen99** [comment] 2017-06-29 18:53
Please post a sample project the duplicates the issue.

**Comment by retrogradeorbit** [comment] 2017-06-30 05:07
https://bitbucket.org/crispinw/coherence_prod_build_test

```$ MIX_ENV=prod mix release --env=prod
Compiling 33 files (.ex)
warning: behaviour Coherence.Messages is undefined
  web/coherence_messages.ex:1

warning: function Coherence.Config.require_current_password/0 is undefined or private
  web/views/coherence/registration_view.ex:29

warning: function Coherence.Config.title/0 is undefined or private
  web/views/coherence/layout_view.ex:10

Generated coherence_demo app
==> Assembling release..
==> Building release coherence_demo:0.0.1 using environment prod
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :earmark
    :ex_machina
    :geo
    :jsx
    :mcd
    :plug_session_memcached
    :transit

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Including ERTS 9.0 from /usr/lib/erlang/erts-9.0
==> Release failed, during .boot generation:
        Duplicated modules: 
    	'Elixir.Phoenix.HTML.Safe.DateTime' specified in phoenix_html and phoenix_timex
    	'Elixir.Phoenix.HTML.Safe.Date' specified in phoenix_html and phoenix_timex
```

**Comment by retrogradeorbit** [comment] 2017-06-30 05:08
full deps tree of test project:

```
$ mix deps.tree
coherence_demo
├── faker ~> 0.8.0 (Hex package)
├── gettext ~> 0.13.1 (Hex package)
├── comeonin ~> 2.6.0 (Hex package)
├── poison ~> 3.1.0 (Hex package) *override*
├── jsx ~> 2.8.0 (Hex package) *override*
├── hackney 1.8.0 (Hex package) *override*
│   ├── certifi 1.1.0 (Hex package)
│   ├── idna 4.0.0 (Hex package)
│   ├── metrics 1.0.1 (Hex package)
│   ├── mimerl 1.0.2 (Hex package)
│   └── ssl_verify_fun 1.1.1 (Hex package)
├── ex_aws ~> 1.1.2 (Hex package)
│   ├── hackney 1.6.3 or 1.6.5 or 1.7.1 (Hex package)
│   ├── jsx ~> 2.8 (Hex package)
│   └── poison >= 1.2.0 (Hex package)
├── excoveralls ~> 0.5 (Hex package)
│   ├── exjsx >= 3.0.0 (Hex package)
│   │   └── jsx ~> 2.8.0 (Hex package)
│   └── hackney >= 0.12.0 (Hex package)
├── facebook ~> 0.13.2 (Hex package)
│   ├── hackney ~> 1.6 (Hex package)
│   └── json >= 0.3.3 (Hex package)
├── timex ~> 3.1.13 (Hex package) *override*
│   ├── combine ~> 0.7 (Hex package)
│   ├── gettext ~> 0.10 (Hex package)
│   └── tzdata ~> 0.1.8 or ~> 0.5 (Hex package)
│       └── hackney ~> 1.0 (Hex package)
├── earmark ~> 1.2.1 (Hex package)
├── httpoison ~> 0.11.2 (Hex package) *override*
│   └── hackney ~> 1.8.0 (Hex package)
├── twilex ~> 0.0.2 (Hex package) *override*
│   ├── httpoison ~> 0.8.0 (Hex package)
│   └── poison ~> 2.0 (Hex package)
├── phoenix_pubsub ~> 1.0.1 (Hex package)
├── oauth2 ~> 0.9 (Hex package)
│   └── hackney ~> 1.7 (Hex package)
├── cowboy ~> 1.0.0 (Hex package)
│   ├── cowlib ~> 1.0.0 (Hex package)
│   └── ranch ~> 1.0 (Hex package)
├── transit (https://github.com/isaiah/transit-erlang.git)
│   ├── msgpack ~r/.*/ (git://github.com/msgpack/msgpack-erlang.git)
│   └── jsx ~r/.*/ (https://github.com/talentdeficit/jsx.git)
├── bureaucrat ~> 0.1.4 (Hex package)
│   └── plug ~> 0.14 or ~> 1.0 (Hex package)
│       ├── cowboy ~> 1.0.1 or ~> 1.1 (Hex package)
│       └── mime ~> 1.0 (Hex package)
├── phoenix_html ~> 2.9.3 (Hex package) *override*
│   └── plug ~> 1.0 (Hex package)
├── swoosh ~> 0.7.0 (Hex package)
│   ├── cowboy ~> 1.0 (Hex package)
│   ├── hackney ~> 1.6 (Hex package)
│   ├── plug ~> 1.1 (Hex package)
│   └── poison ~> 1.5 or ~> 2.0 or ~> 3.0 (Hex package)
├── phoenix ~> 1.2.3 (Hex package)
│   ├── cowboy ~> 1.0 (Hex package)
│   ├── phoenix_pubsub ~> 1.0 (Hex package)
│   ├── plug ~> 1.4 or ~> 1.3.3 or ~> 1.2.4 or ~> 1.1.8 or ~> 1.0.5 (Hex package)
│   └── poison ~> 1.5 or ~> 2.0 (Hex package)
├── phoenix_live_reload ~> 1.0.8 (Hex package)
│   ├── fs ~> 0.9.1 (Hex package)
│   └── phoenix ~> 1.0 or ~> 1.2-rc (Hex package)
├── lager (https://github.com/basho/lager.git) *override*
│   └── goldrush ~r/.*/ (https://github.com/basho/goldrush.git)
├── postgrex ~> 0.13.2 (Hex package)
│   ├── connection ~> 1.0 (Hex package)
│   ├── db_connection ~> 1.1 (Hex package)
│   │   ├── connection ~> 1.0.2 (Hex package)
│   │   └── poolboy ~> 1.5 (Hex package)
│   └── decimal ~> 1.0 (Hex package)
├── ex_machina ~> 2.0.0 (Hex package)
│   └── ecto ~> 2.1 (Hex package)
│       ├── db_connection ~> 1.1 (Hex package)
│       ├── decimal ~> 1.2 (Hex package)
│       ├── poison ~> 2.2 or ~> 3.0 (Hex package)
│       ├── poolboy ~> 1.5 (Hex package)
│       └── postgrex ~> 0.13.0 (Hex package)
├── timex_ecto ~> 3.1.1 (Hex package) *override*
│   ├── ecto ~> 2.1.0 (Hex package)
│   └── timex ~> 3.0 (Hex package)
├── coherence ~> 0.3.1 (Hex package)
│   ├── comeonin ~> 2.4 (Hex package)
│   ├── ecto ~> 2.0 (Hex package)
│   ├── gettext ~> 0.11 (Hex package)
│   ├── phoenix ~> 1.2 (Hex package)
│   ├── phoenix_html ~> 2.6 (Hex package)
│   ├── phoenix_swoosh ~> 0.1.3 (Hex package)
│   │   ├── phoenix ~> 1.0 (Hex package)
│   │   ├── phoenix_html ~> 2.2 (Hex package)
│   │   └── swoosh ~> 0.1 (Hex package)
│   ├── phoenix_timex ~> 1.0.0 (Hex package)
│   │   ├── phoenix_html ~> 2.5 (Hex package)
│   │   └── timex ~> 2.1 (Hex package)
│   ├── timex_ecto ~> 1.1 (Hex package)
│   └── uuid ~> 1.0 (Hex package)
├── distillery ~> 1.4.0 (Hex package)
├── mcd (https://github.com/EchoTeam/mcd.git)
│   ├── lager 2.0.1 (git://github.com/basho/lager.git)
│   ├── corman ~r/1.0.*/ (git://github.com/EchoTeam/corman.git)
│   └── dht_ring ~r/1.0.*/ (git://github.com/EchoTeam/dht_ring.git)
│       └── lager 2.0.1 (git://github.com/basho/lager.git)
├── plug_session_memcached (https://github.com/IgnatiusT/plug-session-memcached.git)
│   ├── cowboy ~> 1.0.0 (Hex package)
│   ├── plug >= 0.13.0 (Hex package)
│   ├── mcd (https://github.com/EchoTeam/mcd.git)
│   ├── earmark >= 0.0.0 (Hex package)
│   └── ex_doc >= 0.10.0 (Hex package)
│       └── earmark ~> 1.1 (Hex package)
├── geo ~> 1.4.1 (Hex package)
│   ├── ecto ~> 2.1 (Hex package)
│   ├── poison ~> 1.5 or ~> 2.0 or ~> 3.0 (Hex package)
│   └── postgrex ~> 0.13 (Hex package)
└── phoenix_ecto ~> 3.2.0 (Hex package)
    ├── ecto ~> 2.1 (Hex package)
    ├── phoenix_html ~> 2.9 (Hex package)
    └── plug ~> 1.0 (Hex package)

```

**Comment by retrogradeorbit** [comment] 2017-06-30 05:10
Let me know if this is a phoenix issue and if so I'll go file a bug over there.

**Comment by smpallen99** [comment] 2017-07-03 02:41
I just added distillery to [coherence_demo](https://github.com/smpallen99/coherence_demo) and I can build release for both dev and prod environments. I'm closing this this issue since you have not provided a sample project that reproduces the issue. If you reopen, make sure you provide a link to a complete project that reproduces the issue.

**Closed by smpallen99** 2017-07-03 02:41 UTC
