### ISSUE TITLE
Should validate e-mail address

### ISSUE THREAD

**Issue by scouten** [smpallen99/coherence#70] opened 2016-10-10 20:12 UTC
You can complete the `/registrations/new` form with an obviously-wrong e-mail address (missing `@` as an example) and it will accept that, even though no mail sent to that address can ever get through.

Seems like some validation should be performed.

**Comment by smpallen99** [comment] 2016-10-15 15:50
Agree

**Comment by agustif** [comment] 2016-10-15 19:28
Which levels of validation are we going to accept?

Good format "string" <> "@" <> "domain.ltd"
restricted only to known/existant ltd? Could be problematic since the rise of buy your own top level domain .whatever

A second step could be to retrieve the DNS records of the email domain, and check for mx records and such that would ensure that at least some kind of email redirect/server would be contacted if an email was to be sent.

What else can be done to ensure mail validation?

Wouldn't be best to have a simple user-flow for wrongly introduced emails, a la twitter or such where you can change your email address if you haven't confirmed it yet, and you get a permanent flashy-type-message remembering you the email you typed and that it isn't confirmed yet.

My point is, emails get badly typed all the time, having 2 email inputs in the form is a PITA in UX.

We should go all OTP and assume bad emails will get inputed, and allow for the user to correct that wrong without caring about email validation at all, maybe some basic kind of stuff like has an @ and ends in .something would be enough

**Comment by DavidVII** [comment] 2016-10-18 03:10
There seems to be some format validation going on in the [invitation](https://github.com/smpallen99/coherence/blob/master/web/models/invitation.ex#L23) module. Should the same thing be added to the user model generator?

Another issue here too is that if someone already has a user model in place, then they would have to be responsible for adding format validation, right?

**Comment by egeersoz** [comment] 2016-11-02 18:52
In my opinion, just check for an `@` sign. Everything else is bound to be error-prone, since emails can be insanely complex. See here: http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address

**Comment by Mehonoshin** [comment] 2016-11-10 14:10
PR is merged, I suppose that this issue should be closed.
Project has too many open issues, can be tricky to find which one is solved, and which is not.

**Closed** 2016-11-10 21:15 UTC
Labels: bug
